### ISSUE TITLE
Pictures, positions and more not showing

### ISSUE THREAD

**Issue by Yupie** [xAranaktu/FIFA-Tracker#5]
Whenever I log in, a lot of information about the players disappear like in the screenshot I attached. Positions aren't showing, the pictures are gone, badges don't show etc.
![screenshot 2019-01-23 at 14 56 29](https://user-images.githubusercontent.com/7197687/51611349-54489180-1f1f-11e9-86d6-9c04b6fc9b8e.png)

And whenever I try to search for a player it says that no results were found, even if I only put the minimum overall to 50 for example.

I'm playing on fifa 18 with a couple seasons in.

What can I do to solve this? Re-upload the save files?

**Comment by xAranaktu** [comment]
Looks like Javascript doesn't executed. I got a few questions. Which browser are you using? Do you have any errors in console? What's your username on the website? It's working fine when you are logged out? Did you tried different browsers? Maybe you have extension which is blocking js execution?

**Comment by Yupie** [comment]
I am using firefox, but I found out that uBlock origin was blocking the javascript.
Disabling the adblocker worked.

Thanks for your help and for developing this great tool!

**Comment by xAranaktu** [comment]
Okay. So I'm closing this issue. :)
